api_key_env: CROWDIN_API_KEY
project_identifier: rancher-ui
base_path: /
preserve_hierarchy: false

files:
- source: /translations/en-us.json
  translation: "/translations/%original_file_name%"
  ignore:
     - "/**/*.md"
  type: yaml
  update_option: update_as_unapproved
  languages_mapping:
     locale:
       de-DE: de-de
       en-US: en-us
       fa-IR: fa-ir
       fr-FR: fr-fr
       ja-JP: ja-jp
       pt-BR: pt-br
       ru-RU: u-ru
       uk-UA: uk-ua
       zh-CN: zh-hans
